language: julia
os:
    # Temporarily commenting out osx because of Homebrew installation issue
    # of gcc 8.x. This causes the HDF5 build to attempt to build it from scratch
    # by downloading all of xcode which Travis CI then kills because it takes too long.
    # Refer to Matt Bauman's comment on JuliaIO/HDF5.jl issue 483, and
    # Andreas Noack's issue 27751 on Homebrew/homebrew-core.
    #- osx
    - linux
julia:
    - 1
notifications:
    email: false
addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0
    homebrew:
      packages:
      - hdf5
script:
    - julia --color=yes -e 'using Pkg; Pkg.build()'
    - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
branches:
  only:
    - master
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("StateSpaceRoutines")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
